Modify how the plugin handles remote meta-data
so it turns out you can't run a plugin multiple times ,so
I've jammed the remote stuff into a new parameter
called 'getRemote'. It'll fail if remoteJobId is not set.

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -6,17 +6,29 @@ set -euo pipefail
 # parse a list of parameters to get and set ENV_VAR_TO_SET: <metadata to get>
 # support cross-job meta-data by supporting the --job key
 job_switch=''
-if [[ -n "${BUILDKITE_PLUGIN_METADATA_JOBID:-}" ]] ; then
-    job_switch="--job $BUILDKITE_PLUGIN_METADATA_JOBID"
-    echo "job_switch: $job_switch"
-    echo "reading meta-data from job id '$BUILDKITE_PLUGIN_METADATA_JOBID'"
+if [[ -n "${BUILDKITE_PLUGIN_METADATA_REMOTEJOBID:-}" ]] ; then
+    job_switch="--job $BUILDKITE_PLUGIN_METADATA_REMOTEJOBID"
 fi
 
 while IFS='=' read -r name _ ; do
   if [[ $name =~ ^(BUILDKITE_PLUGIN_METADATA_GET_[0-9]+) ]] ; then
     echo "fetching meta-data value [${!name}]"
-    metadata_value=$(buildkite-agent meta-data get ${!name} $job_switch)
+    metadata_value=$(buildkite-agent meta-data get ${!name})
     echo "export ${!name}=$metadata_value"
     export ${!name}=$metadata_value  
+
+  elif [[ $name =~ ^(BUILDKITE_PLUGIN_METADATA_GETREMOTE_[0-9]+) ]] ; then
+    if [[ -z "${BUILDKITE_PLUGIN_METADATA_REMOTEJOBID:-}" ]] ; then
+      echo "Missing remoteJobId value when attempting to fetch remote meta-data"
+      exit 1
+    else
+      job_switch="--job $BUILDKITE_PLUGIN_METADATA_REMOTEJOBID"
+      echo "reading meta-data from job id '$BUILDKITE_PLUGIN_METADATA_REMOTEJOBID'"
+      echo "fetching meta-data value [${!name}]"
+      echo "buildkite-agent meta-data get ${!name} $job_switch"
+      metadata_value=$(buildkite-agent meta-data get ${!name} $job_switch)
+      echo "export ${!name}=$metadata_value"
+      export ${!name}=$metadata_value  
+    fi
   fi
 done < <(env | sort)
